#!/usr/bin/env node
// Raise the generated iOS project's minimum OS version.
//
// `ios/` holds only HANDOFF.md: the native Xcode project, its Podfile and its
// Info.plist are generated by the Capacitor CLI on every CI run ('cap add ios'
// / 'cap sync ios'). Capacitor 6 scaffolds them at iOS 13.0, and MinimumOSVersion
// in the built Info.plist is whatever IPHONEOS_DEPLOYMENT_TARGET said at archive
// time. App Store Connect answers a 13.0 upload with:
//
//   ITMS-90068: This bundle is invalid. The value provided for the key
//   MinimumOSVersion is not acceptable.
//
// So the bump cannot be committed once -- it has to be re-applied after the
// Capacitor sync and before `pod install`, on every run. That is this script.
//
// It only ever raises: if a future Capacitor scaffolds a higher target than
// MIN_IOS_VERSION, that target is left alone rather than being pulled back down.
//
// Run from the repo root, after 'cap sync ios':
//   node scripts/ios-min-os.mjs      # then: (cd ios/App && pod install)
//
// The Podfile edit is why `pod install` has to run again afterwards: the pods
// were already resolved against the old platform line by the sync.
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const TAG = '[ios-min-os]';
const root = join(dirname(fileURLToPath(import.meta.url)), '..');

// Apple rejects anything lower with ITMS-90068. Overridable so the floor can be
// raised from the workflow without touching this file.
const MIN = (process.env.MIN_IOS_VERSION || '15.0').trim();

const PODFILE = join(root, 'ios', 'App', 'Podfile');
const PBXPROJ = join(root, 'ios', 'App', 'App.xcodeproj', 'project.pbxproj');

function fail(title, detail) {
  if (process.env.GITHUB_ACTIONS) {
    console.log(`::error title=${title}::${detail.replace(/\s+/g, ' ').trim()}`);
  }
  console.error(`${TAG} ${title}: ${detail}`);
  process.exit(1);
}

// '13.0' < '15.0' but '9.0' > '15.0' as strings, so compare componentwise.
function isLower(version, floor) {
  const a = String(version).split('.').map(Number);
  const b = String(floor).split('.').map(Number);
  for (let i = 0; i < Math.max(a.length, b.length); i++) {
    const x = a[i] || 0;
    const y = b[i] || 0;
    if (x !== y) return x < y;
  }
  return false;
}

if (!/^\d+(\.\d+)*$/.test(MIN)) {
  fail('MIN_IOS_VERSION is not a version', `Expected something like "15.0", got "${MIN}".`);
}

// ---------------------------------------------------------------------------
// Podfile — the platform line every pod target inherits.

if (!existsSync(PODFILE)) {
  fail(
    'Podfile missing',
    `Expected ${PODFILE} after the Capacitor sync. Without it the pods build against ` +
      'their own defaults and the archive keeps the old minimum OS version.'
  );
}

const podfile = readFileSync(PODFILE, 'utf8');
const platformLine = /^(\s*platform :ios, ')([\d.]+)(')/m;
const platformMatch = podfile.match(platformLine);

if (!platformMatch) {
  fail(
    'No platform line in the Podfile',
    "Could not find a \"platform :ios, '<version>'\" line to raise. The Capacitor " +
      'Podfile template changed shape; update scripts/ios-min-os.mjs to match it.'
  );
}

if (isLower(platformMatch[2], MIN)) {
  writeFileSync(PODFILE, podfile.replace(platformLine, `$1${MIN}$3`), 'utf8');
  console.log(`${TAG} Podfile platform :ios ${platformMatch[2]} -> ${MIN}`);
} else {
  console.log(`${TAG} Podfile platform :ios already ${platformMatch[2]} (floor ${MIN}) — left alone`);
}

// ---------------------------------------------------------------------------
// Xcode project — the app target's own deployment target, which is what ends up
// in the built Info.plist as MinimumOSVersion.

if (!existsSync(PBXPROJ)) {
  fail(
    'Xcode project missing',
    `Expected ${PBXPROJ} after the Capacitor sync. The archive would ship whatever ` +
      'minimum OS version the generated project happened to carry.'
  );
}

const pbxproj = readFileSync(PBXPROJ, 'utf8');
let seen = 0;
let raised = 0;
const patched = pbxproj.replace(/IPHONEOS_DEPLOYMENT_TARGET = ([\d.]+);/g, (whole, current) => {
  seen++;
  if (!isLower(current, MIN)) return whole;
  raised++;
  return `IPHONEOS_DEPLOYMENT_TARGET = ${MIN};`;
});

if (seen === 0) {
  fail(
    'No deployment target in the Xcode project',
    'project.pbxproj declares no IPHONEOS_DEPLOYMENT_TARGET, so nothing was raised and ' +
      'the build would silently keep Xcode’s default. The Capacitor project template ' +
      'changed; update scripts/ios-min-os.mjs to match it.'
  );
}

if (raised > 0) writeFileSync(PBXPROJ, patched, 'utf8');
console.log(
  `${TAG} project.pbxproj: raised ${raised} of ${seen} IPHONEOS_DEPLOYMENT_TARGET ` +
    `setting(s) to ${MIN}${raised === seen ? '' : ' (the rest were already at or above it)'}`
);
console.log(`${TAG} minimum iOS version is ${MIN}`);
